// Reference tests for sample_correlation/demean_columns (ADR-020 layer
// 1). The 3-observation, 2-asset case here is hand-derived by exact
// arithmetic (see the shrinkage_test.cpp header comment for the same
// dataset's Ledoit-Wolf derivation) - not generated by the code under
// test.

#include <gm-geometry/correlation.hpp>

#include <catch2/catch_test_macros.hpp>

#include <cmath>

using gm::geometry::demean_columns;
using gm::geometry::sample_correlation;

namespace {
constexpr double kTol = 1e-9;
}

TEST_CASE("demean_columns subtracts each column's own mean", "[correlation]") {
    Eigen::MatrixXd x(3, 2);
    x << 1, 2, 2, 1, 3, 6;  // col0 mean=2, col1 mean=3

    auto result = demean_columns(x);
    REQUIRE(result.has_value());
    CHECK(std::abs((*result)(0, 0) - (-1.0)) < kTol);
    CHECK(std::abs((*result)(1, 0) - 0.0) < kTol);
    CHECK(std::abs((*result)(2, 0) - 1.0) < kTol);
    CHECK(std::abs((*result)(0, 1) - (-1.0)) < kTol);
    CHECK(std::abs((*result)(1, 1) - (-2.0)) < kTol);
    CHECK(std::abs((*result)(2, 1) - 3.0) < kTol);
}

TEST_CASE("sample_correlation matches hand-computed value for a small fixed dataset",
          "[correlation]") {
    // Same X as demean_columns above. Demeaned: [[-1,-1],[0,-2],[1,3]].
    // cov(0,1) [T-1=2 divisor] = ((-1)(-1) + 0*(-2) + 1*3) / 2 = 4/2 = 2
    // var(0) = (1+0+1)/2 = 1; var(1) = (1+4+9)/2 = 7
    // rho(0,1) = 2 / sqrt(1*7) = 2/sqrt(7)
    Eigen::MatrixXd x(3, 2);
    x << 1, 2, 2, 1, 3, 6;

    auto result = sample_correlation(x);
    REQUIRE(result.has_value());

    double expected_rho = 2.0 / std::sqrt(7.0);
    CHECK(std::abs((*result)(0, 1) - expected_rho) < kTol);
    CHECK(std::abs((*result)(1, 0) - expected_rho) < kTol);
    CHECK(std::abs((*result)(0, 0) - 1.0) < kTol);
    CHECK(std::abs((*result)(1, 1) - 1.0) < kTol);
}

TEST_CASE("perfectly correlated columns give correlation exactly 1", "[correlation]") {
    Eigen::MatrixXd x(4, 2);
    x.col(0) << 1, 2, 3, 4;
    x.col(1) << 10, 20, 30, 40;  // col1 = 10 * col0, perfectly linearly related

    auto result = sample_correlation(x);
    REQUIRE(result.has_value());
    CHECK(std::abs((*result)(0, 1) - 1.0) < kTol);
}

TEST_CASE("perfectly anti-correlated columns give correlation exactly -1", "[correlation]") {
    Eigen::MatrixXd x(4, 2);
    x.col(0) << 1, 2, 3, 4;
    x.col(1) << -1, -2, -3, -4;

    auto result = sample_correlation(x);
    REQUIRE(result.has_value());
    CHECK(std::abs((*result)(0, 1) - (-1.0)) < kTol);
}

TEST_CASE("fewer than 2 observations is rejected", "[correlation]") {
    Eigen::MatrixXd x(1, 2);
    x << 1, 2;
    auto result = sample_correlation(x);
    REQUIRE_FALSE(result.has_value());
    CHECK(result.error().code == gm::ErrorCode::kInvalidArgument);
}

TEST_CASE("a zero-variance column is rejected rather than producing NaN/Inf", "[correlation]") {
    Eigen::MatrixXd x(3, 2);
    x.col(0) << 1, 2, 3;
    x.col(1) << 5, 5, 5;  // constant column, zero variance

    auto result = sample_correlation(x);
    REQUIRE_FALSE(result.has_value());
    CHECK(result.error().code == gm::ErrorCode::kInvalidArgument);
}
