// Reference test for ledoit_wolf_shrink_correlation (ADR-020 layer 1).
//
// The T=3, N=2 case here is hand-derived by exact arithmetic through
// the full Ledoit-Wolf (2004) Section 2 shrinkage-to-identity formula -
// not generated by the code under test. Worked by hand from
// X = [[1,2],[2,1],[3,6]]:
//   demeaned = [[-1,-1],[0,-2],[1,3]]; var(0)=1, var(1)=7 (T-1 divisor)
//   standardized col1 by /sqrt(7): [[-1,-1/sqrt7],[0,-2/sqrt7],[1,3/sqrt7]]
//   S (LW's 1/T divisor) = [[2/3, 4/(3*sqrt7)], [4/(3*sqrt7), 2/3]]
//   mu = trace(S)/2 = 2/3
//   d2 = ||S - mu*I||_F^2 = 2*(4/(3*sqrt7))^2 = 32/63
//   b_bar2 = 8/27 (via the closed-form sum over the 3 rows)
//   b2 = min(b_bar2, d2) = 8/27 (8/27 ~ 0.2963 < 32/63 ~ 0.5079)
//   delta = b2/d2 = (8/27)/(32/63) = 7/12 exactly
//   shrunk(0,1) = (1-delta)*S(0,1) = (5/12)*(4/(3*sqrt7)) = 5/(9*sqrt7)

#include <gm-geometry/shrinkage.hpp>

#include <catch2/catch_test_macros.hpp>

#include <cmath>

using gm::geometry::ledoit_wolf_shrink_correlation;

namespace {
constexpr double kTol = 1e-9;
}

TEST_CASE("Ledoit-Wolf shrinkage matches hand-derived values for a small fixed dataset",
          "[shrinkage]") {
    Eigen::MatrixXd x(3, 2);
    x << 1, 2, 2, 1, 3, 6;

    auto result = ledoit_wolf_shrink_correlation(x);
    REQUIRE(result.has_value());

    double expected_delta = 7.0 / 12.0;
    CHECK(std::abs(result->shrinkage_intensity - expected_delta) < kTol);

    double expected_off_diag = 5.0 / (9.0 * std::sqrt(7.0));
    CHECK(std::abs(result->correlation(0, 1) - expected_off_diag) < 1e-8);
    CHECK(std::abs(result->correlation(1, 0) - expected_off_diag) < 1e-8);
}

TEST_CASE("shrinkage_intensity is always in [0, 1]", "[shrinkage]") {
    Eigen::MatrixXd x(5, 3);
    x << 1, 2, 3, 2, 1, 5, 3, 4, 2, 4, 3, 8, 5, 6, 1;

    auto result = ledoit_wolf_shrink_correlation(x);
    REQUIRE(result.has_value());
    CHECK(result->shrinkage_intensity >= 0.0);
    CHECK(result->shrinkage_intensity <= 1.0);
}

TEST_CASE("shrunk correlation always has an exact unit diagonal", "[shrinkage]") {
    Eigen::MatrixXd x(6, 4);
    x << 1, 5, 2, 9, 2, 3, 4, 1, 3, 8, 1, 4, 1, 2, 6, 7, 4, 4, 3, 2, 5, 1, 7, 3;

    auto result = ledoit_wolf_shrink_correlation(x);
    REQUIRE(result.has_value());
    for (int i = 0; i < result->correlation.rows(); ++i) {
        CHECK(std::abs(result->correlation(i, i) - 1.0) < kTol);
    }
}

TEST_CASE("shrunk correlation is exactly symmetric", "[shrinkage]") {
    Eigen::MatrixXd x(6, 4);
    x << 1, 5, 2, 9, 2, 3, 4, 1, 3, 8, 1, 4, 1, 2, 6, 7, 4, 4, 3, 2, 5, 1, 7, 3;

    auto result = ledoit_wolf_shrink_correlation(x);
    REQUIRE(result.has_value());
    Eigen::MatrixXd diff = result->correlation - result->correlation.transpose();
    CHECK(diff.cwiseAbs().maxCoeff() < kTol);
}

TEST_CASE("fewer than 2 observations is rejected", "[shrinkage]") {
    Eigen::MatrixXd x(1, 2);
    x << 1, 2;
    auto result = ledoit_wolf_shrink_correlation(x);
    REQUIRE_FALSE(result.has_value());
    CHECK(result.error().code == gm::ErrorCode::kInvalidArgument);
}

TEST_CASE("a zero-variance column is rejected", "[shrinkage]") {
    Eigen::MatrixXd x(3, 2);
    x.col(0) << 1, 2, 3;
    x.col(1) << 5, 5, 5;
    auto result = ledoit_wolf_shrink_correlation(x);
    REQUIRE_FALSE(result.has_value());
    CHECK(result.error().code == gm::ErrorCode::kInvalidArgument);
}
