// Reference tests for gm-view's camera math (ADR-020 layer 1 applied to
// the viewer, per the M3 code review's finding that this code had zero
// test coverage and its correctness could only be judged from
// screenshots). The look-at case below is hand-derived by exact
// arithmetic - not generated by the code under test - and specifically
// checks the thing the review flagged as its own low-confidence
// concern: whether the column-major storage layout is actually correct
// (it is; the review's suggested "fix" would have been the transpose,
// which inverts an orthogonal rotation matrix).
//
// Hand derivation: eye=(0,0,5), target=(0,0,0), up=(0,1,0).
//   forward = normalize(target-eye) = (0,0,-1)
//   right   = normalize(cross(forward,up)) = cross((0,0,-1),(0,1,0)) = (1,0,0)
//   new_up  = cross(right,forward) = cross((1,0,0),(0,0,-1)) = (0,1,0)
// So the view matrix should be identity-like with only translation:
// applying it to the eye point (0,0,5,1) must give the view-space
// origin (0,0,0,1) - a camera is always at the origin of its own view
// space - and applying it to the target (0,0,0,1) must give (0,0,-5,1)
// - 5 units in front of the camera along view-space -Z.

#include "../camera.hpp"

#include <catch2/catch_test_macros.hpp>

#include <cmath>

using gm::view::mat4_identity;
using gm::view::mat4_look_at;
using gm::view::mat4_multiply;
using gm::view::mat4_perspective;
using gm::view::Mat4;
using gm::view::OrbitCamera;

namespace {
constexpr float kTol = 1e-5f;

// v is (x,y,z,w); m is column-major (index = col*4+row), matching what
// glUniformMatrix4fv(..., transpose=GL_FALSE, ...) expects.
std::array<float, 4> transform(const Mat4& m, std::array<float, 4> v) {
    std::array<float, 4> result{};
    for (int row = 0; row < 4; ++row) {
        float sum = 0.0f;
        for (int col = 0; col < 4; ++col) sum += m[static_cast<std::size_t>(col * 4 + row)] * v[static_cast<std::size_t>(col)];
        result[static_cast<std::size_t>(row)] = sum;
    }
    return result;
}
} // namespace

TEST_CASE("mat4_identity is the identity matrix", "[camera]") {
    Mat4 m = mat4_identity();
    for (int i = 0; i < 16; ++i) {
        float expected = (i % 5 == 0) ? 1.0f : 0.0f;  // diagonal entries are indices 0,5,10,15
        CHECK(std::abs(m[static_cast<std::size_t>(i)] - expected) < kTol);
    }
}

TEST_CASE("mat4_multiply by identity is a no-op on both sides", "[camera]") {
    Mat4 identity = mat4_identity();
    Mat4 m = mat4_perspective(1.0f, 1.5f, 0.1f, 100.0f);

    Mat4 left = mat4_multiply(identity, m);
    Mat4 right = mat4_multiply(m, identity);
    for (int i = 0; i < 16; ++i) {
        CHECK(std::abs(left[static_cast<std::size_t>(i)] - m[static_cast<std::size_t>(i)]) < kTol);
        CHECK(std::abs(right[static_cast<std::size_t>(i)] - m[static_cast<std::size_t>(i)]) < kTol);
    }
}

TEST_CASE("mat4_look_at maps the eye to the view-space origin", "[camera]") {
    Mat4 view = mat4_look_at(0, 0, 5, 0, 0, 0, 0, 1, 0);
    auto eye_in_view = transform(view, {0, 0, 5, 1});
    CHECK(std::abs(eye_in_view[0] - 0.0f) < kTol);
    CHECK(std::abs(eye_in_view[1] - 0.0f) < kTol);
    CHECK(std::abs(eye_in_view[2] - 0.0f) < kTol);
    CHECK(std::abs(eye_in_view[3] - 1.0f) < kTol);
}

TEST_CASE("mat4_look_at maps the target to 5 units in front along -Z", "[camera]") {
    // Hand-derived: with eye=(0,0,5) looking at the origin with up=(0,1,0),
    // right=(1,0,0) and new_up=(0,1,0) come out exactly axis-aligned
    // (see the file header derivation), so the target must land at
    // exactly (0,0,-5,1) in view space - not just "some negative Z."
    Mat4 view = mat4_look_at(0, 0, 5, 0, 0, 0, 0, 1, 0);
    auto target_in_view = transform(view, {0, 0, 0, 1});
    CHECK(std::abs(target_in_view[0] - 0.0f) < kTol);
    CHECK(std::abs(target_in_view[1] - 0.0f) < kTol);
    CHECK(std::abs(target_in_view[2] - (-5.0f)) < kTol);
    CHECK(std::abs(target_in_view[3] - 1.0f) < kTol);
}

TEST_CASE("mat4_perspective maps a point on the near plane center to NDC z=-1", "[camera]") {
    // Standard OpenGL NDC convention: after the perspective divide, a
    // point exactly on the near plane maps to z_ndc = -1.
    float z_near = 0.5f, z_far = 100.0f;
    Mat4 proj = mat4_perspective(1.0f, 1.0f, z_near, z_far);
    // A point straight ahead on the near plane, in view space:
    // (0, 0, -z_near, 1) (camera looks down -Z).
    auto clip = transform(proj, {0.0f, 0.0f, -z_near, 1.0f});
    REQUIRE(std::abs(clip[3]) > 1e-6f);
    float ndc_z = clip[2] / clip[3];
    CHECK(std::abs(ndc_z - (-1.0f)) < 1e-3f);
}

TEST_CASE("mat4_perspective maps a point on the far plane center to NDC z=+1", "[camera]") {
    float z_near = 0.5f, z_far = 100.0f;
    Mat4 proj = mat4_perspective(1.0f, 1.0f, z_near, z_far);
    auto clip = transform(proj, {0.0f, 0.0f, -z_far, 1.0f});
    REQUIRE(std::abs(clip[3]) > 1e-6f);
    float ndc_z = clip[2] / clip[3];
    CHECK(std::abs(ndc_z - 1.0f) < 1e-3f);
}

TEST_CASE("OrbitCamera places the eye at the expected distance from target", "[camera]") {
    OrbitCamera cam;
    cam.target_x = 1.0f;
    cam.target_y = 2.0f;
    cam.target_z = 3.0f;
    cam.distance = 7.0f;
    cam.yaw = 0.0f;
    cam.pitch = 0.0f;

    // yaw=0, pitch=0 -> eye = target + (0, 0, distance) per the
    // spherical-to-Cartesian formula (sin(0)=0, cos(0)=1).
    Mat4 view = cam.view_matrix();
    // The eye, wherever it is, must transform to the view-space origin -
    // reuse that same invariant to pin down where the camera actually
    // computed the eye to be, without duplicating its internal formula.
    auto eye_guess_in_view = transform(view, {1.0f, 2.0f, 3.0f + 7.0f, 1.0f});
    CHECK(std::abs(eye_guess_in_view[0]) < kTol);
    CHECK(std::abs(eye_guess_in_view[1]) < kTol);
    CHECK(std::abs(eye_guess_in_view[2]) < kTol);
}

TEST_CASE("OrbitCamera pitch is clamped and never produces a degenerate view matrix", "[camera]") {
    OrbitCamera cam;
    cam.orbit(0.0f, 100.0f);  // absurdly large delta, must clamp not overflow
    CHECK(cam.pitch <= 1.5f);
    CHECK(cam.pitch >= -1.5f);

    cam.orbit(0.0f, -200.0f);
    CHECK(cam.pitch >= -1.5f);
    CHECK(cam.pitch <= 1.5f);

    // Even at the clamp boundary, the view matrix must be finite (no
    // NaN from a degenerate cross product when the eye-to-target vector
    // is parallel to the up vector).
    Mat4 view = cam.view_matrix();
    for (float v : view) CHECK(std::isfinite(v));
}

TEST_CASE("OrbitCamera zoom never goes to or below zero distance", "[camera]") {
    OrbitCamera cam;
    cam.distance = 1.0f;
    cam.zoom(-100.0f);  // large zoom-in request
    CHECK(cam.distance > 0.0f);
}
